[package]
name = "fluvial"
version = "0.3.0"
authors = ["alexjago"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Visualise stop-by-stop passenger patronage over routes."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rust-hsluv = "0.1.4"
clap = "2.33.3"
serde_rusqlite = "0.26.0"
serde_derive = "1.0.117"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.13"
ansi-escapes = "0.1.0"

[dependencies.rusqlite]
version = "0.24.1"
features = ["csvtab"]